version: "3.7"

services:
  app: 
    build: .
    container_name: doctor-api
    command: npm run start:dev
    ports: 
      - '3000:3000'
    volumes: 
      - .:/usr/app
    environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres123
    - DB_DATABASE=doctor_db
  db:
    image: postgres
    container_name: postgresdb
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres123
        POSTGRES_DB: doctor_db
    ports:
        - 5432:5432
  db-admin:
    image: dpage/pgadmin4
    container_name: pgadmin_4
    restart: always
    ports:
        - 9090:80
    depends_on:
        - db
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: postgres123